// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type Todo struct {
	ID        int64         `json:"id"`
	UserID    int64         `json:"user_id"`
	ProjectID sql.NullInt64 `json:"project_id"`
	Title     string        `json:"title"`
	Notes     string        `json:"notes"`
	Priority  int32         `json:"priority"`
	Status    string        `json:"status"`
	DueAt     sql.NullTime  `json:"due_at"`
	CreatedAt time.Time     `json:"created_at"`
	UpdatedAt time.Time     `json:"updated_at"`
}

type TodoProject struct {
	ID        int64     `json:"id"`
	UserID    int64     `json:"user_id"`
	Name      string    `json:"name"`
	Color     string    `json:"color"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type TodoTag struct {
	ID     int64  `json:"id"`
	UserID int64  `json:"user_id"`
	Name   string `json:"name"`
}

type TodoTagMap struct {
	TodoID int64 `json:"todo_id"`
	TagID  int64 `json:"tag_id"`
}
