// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: todo.sql

package db

import (
	"context"
	"database/sql"
)

const addRecurrenceDay = `-- name: AddRecurrenceDay :exec

INSERT INTO todo_recurrence_days (todo_id, weekday)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddRecurrenceDayParams struct {
	TodoID  int64 `json:"todo_id"`
	Weekday int16 `json:"weekday"`
}

// Recurrence weekdays ------------------------------------------------------
func (q *Queries) AddRecurrenceDay(ctx context.Context, arg AddRecurrenceDayParams) error {
	_, err := q.db.ExecContext(ctx, addRecurrenceDay, arg.TodoID, arg.Weekday)
	return err
}

const addTagToTodo = `-- name: AddTagToTodo :exec
INSERT INTO todo_tag_map (todo_id, tag_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddTagToTodoParams struct {
	TodoID int64 `json:"todo_id"`
	TagID  int64 `json:"tag_id"`
}

func (q *Queries) AddTagToTodo(ctx context.Context, arg AddTagToTodoParams) error {
	_, err := q.db.ExecContext(ctx, addTagToTodo, arg.TodoID, arg.TagID)
	return err
}

const clearRecurrenceDays = `-- name: ClearRecurrenceDays :exec
DELETE FROM todo_recurrence_days WHERE todo_id = $1
`

func (q *Queries) ClearRecurrenceDays(ctx context.Context, todoID int64) error {
	_, err := q.db.ExecContext(ctx, clearRecurrenceDays, todoID)
	return err
}

const copyRecurrenceDays = `-- name: CopyRecurrenceDays :exec
INSERT INTO todo_recurrence_days (todo_id, weekday)
SELECT $1, d.weekday FROM todo_recurrence_days d WHERE d.todo_id = $2
ON CONFLICT DO NOTHING
`

type CopyRecurrenceDaysParams struct {
	DstTodoID int64 `json:"dst_todo_id"`
	SrcTodoID int64 `json:"src_todo_id"`
}

// Carries the weekday rule over to a spawned occurrence.
func (q *Queries) CopyRecurrenceDays(ctx context.Context, arg CopyRecurrenceDaysParams) error {
	_, err := q.db.ExecContext(ctx, copyRecurrenceDays, arg.DstTodoID, arg.SrcTodoID)
	return err
}

const copyTodoTags = `-- name: CopyTodoTags :exec
INSERT INTO todo_tag_map (todo_id, tag_id)
SELECT $1, m.tag_id FROM todo_tag_map m WHERE m.todo_id = $2
ON CONFLICT DO NOTHING
`

type CopyTodoTagsParams struct {
	DstTodoID int64 `json:"dst_todo_id"`
	SrcTodoID int64 `json:"src_todo_id"`
}

// Carries the tags of one todo over to another — a spawned occurrence should look
// exactly like the one it replaces.
func (q *Queries) CopyTodoTags(ctx context.Context, arg CopyTodoTagsParams) error {
	_, err := q.db.ExecContext(ctx, copyTodoTags, arg.DstTodoID, arg.SrcTodoID)
	return err
}

const createProject = `-- name: CreateProject :one

INSERT INTO todo_projects (user_id, name, color)
VALUES ($1, $2, $3)
RETURNING id, user_id, name, color, created_at, updated_at
`

type CreateProjectParams struct {
	UserID int64  `json:"user_id"`
	Name   string `json:"name"`
	Color  string `json:"color"`
}

// Projects -----------------------------------------------------------------
func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (TodoProject, error) {
	row := q.db.QueryRowContext(ctx, createProject, arg.UserID, arg.Name, arg.Color)
	var i TodoProject
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTag = `-- name: CreateTag :one

INSERT INTO todo_tags (user_id, name)
VALUES ($1, $2)
RETURNING id, user_id, name
`

type CreateTagParams struct {
	UserID int64  `json:"user_id"`
	Name   string `json:"name"`
}

// Tags ---------------------------------------------------------------------
func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (TodoTag, error) {
	row := q.db.QueryRowContext(ctx, createTag, arg.UserID, arg.Name)
	var i TodoTag
	err := row.Scan(&i.ID, &i.UserID, &i.Name)
	return i, err
}

const createTodo = `-- name: CreateTodo :one

INSERT INTO todos (user_id, project_id, title, notes, priority, status, due_at, estimate_minutes,
                   recurrence_freq, recurrence_interval, recurrence_until, recurrence_remaining,
                   spawned_from_id, position)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13,
        COALESCE((SELECT MAX(position) + 1 FROM todos WHERE user_id = $1), 0))
RETURNING id, user_id, project_id, title, notes, priority, status, due_at, created_at, updated_at, estimate_minutes, position, recurrence_freq, recurrence_interval, spawned_from_id, recurrence_until, recurrence_remaining
`

type CreateTodoParams struct {
	UserID              int64          `json:"user_id"`
	ProjectID           sql.NullInt64  `json:"project_id"`
	Title               string         `json:"title"`
	Notes               string         `json:"notes"`
	Priority            int32          `json:"priority"`
	Status              string         `json:"status"`
	DueAt               sql.NullTime   `json:"due_at"`
	EstimateMinutes     sql.NullInt32  `json:"estimate_minutes"`
	RecurrenceFreq      sql.NullString `json:"recurrence_freq"`
	RecurrenceInterval  int32          `json:"recurrence_interval"`
	RecurrenceUntil     sql.NullTime   `json:"recurrence_until"`
	RecurrenceRemaining sql.NullInt32  `json:"recurrence_remaining"`
	SpawnedFromID       sql.NullInt64  `json:"spawned_from_id"`
}

// Todos --------------------------------------------------------------------
// New todos append to the end of the user's custom order (max position + 1).
func (q *Queries) CreateTodo(ctx context.Context, arg CreateTodoParams) (Todo, error) {
	row := q.db.QueryRowContext(ctx, createTodo,
		arg.UserID,
		arg.ProjectID,
		arg.Title,
		arg.Notes,
		arg.Priority,
		arg.Status,
		arg.DueAt,
		arg.EstimateMinutes,
		arg.RecurrenceFreq,
		arg.RecurrenceInterval,
		arg.RecurrenceUntil,
		arg.RecurrenceRemaining,
		arg.SpawnedFromID,
	)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.Title,
		&i.Notes,
		&i.Priority,
		&i.Status,
		&i.DueAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EstimateMinutes,
		&i.Position,
		&i.RecurrenceFreq,
		&i.RecurrenceInterval,
		&i.SpawnedFromID,
		&i.RecurrenceUntil,
		&i.RecurrenceRemaining,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM todo_projects
WHERE id = $1 AND user_id = $2
`

type DeleteProjectParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteProject(ctx context.Context, arg DeleteProjectParams) error {
	_, err := q.db.ExecContext(ctx, deleteProject, arg.ID, arg.UserID)
	return err
}

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM todo_tags
WHERE id = $1 AND user_id = $2
`

type DeleteTagParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteTag(ctx context.Context, arg DeleteTagParams) error {
	_, err := q.db.ExecContext(ctx, deleteTag, arg.ID, arg.UserID)
	return err
}

const deleteTodo = `-- name: DeleteTodo :exec
DELETE FROM todos
WHERE id = $1 AND user_id = $2
`

type DeleteTodoParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteTodo(ctx context.Context, arg DeleteTodoParams) error {
	_, err := q.db.ExecContext(ctx, deleteTodo, arg.ID, arg.UserID)
	return err
}

const getProject = `-- name: GetProject :one
SELECT id, user_id, name, color, created_at, updated_at FROM todo_projects
WHERE id = $1 AND user_id = $2
`

type GetProjectParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) GetProject(ctx context.Context, arg GetProjectParams) (TodoProject, error) {
	row := q.db.QueryRowContext(ctx, getProject, arg.ID, arg.UserID)
	var i TodoProject
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSpawnedTodo = `-- name: GetSpawnedTodo :one
SELECT id, user_id, project_id, title, notes, priority, status, due_at, created_at, updated_at, estimate_minutes, position, recurrence_freq, recurrence_interval, spawned_from_id, recurrence_until, recurrence_remaining FROM todos
WHERE spawned_from_id = $1 AND user_id = $2
ORDER BY id DESC
LIMIT 1
`

type GetSpawnedTodoParams struct {
	SpawnedFromID sql.NullInt64 `json:"spawned_from_id"`
	UserID        int64         `json:"user_id"`
}

// The successor a recurring occurrence created when it was checked done. Used to
// take it back when the user un-checks the parent within the undo window.
func (q *Queries) GetSpawnedTodo(ctx context.Context, arg GetSpawnedTodoParams) (Todo, error) {
	row := q.db.QueryRowContext(ctx, getSpawnedTodo, arg.SpawnedFromID, arg.UserID)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.Title,
		&i.Notes,
		&i.Priority,
		&i.Status,
		&i.DueAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EstimateMinutes,
		&i.Position,
		&i.RecurrenceFreq,
		&i.RecurrenceInterval,
		&i.SpawnedFromID,
		&i.RecurrenceUntil,
		&i.RecurrenceRemaining,
	)
	return i, err
}

const getTag = `-- name: GetTag :one
SELECT id, user_id, name FROM todo_tags
WHERE id = $1 AND user_id = $2
`

type GetTagParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) GetTag(ctx context.Context, arg GetTagParams) (TodoTag, error) {
	row := q.db.QueryRowContext(ctx, getTag, arg.ID, arg.UserID)
	var i TodoTag
	err := row.Scan(&i.ID, &i.UserID, &i.Name)
	return i, err
}

const getTodo = `-- name: GetTodo :one
SELECT id, user_id, project_id, title, notes, priority, status, due_at, created_at, updated_at, estimate_minutes, position, recurrence_freq, recurrence_interval, spawned_from_id, recurrence_until, recurrence_remaining FROM todos
WHERE id = $1 AND user_id = $2
`

type GetTodoParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) GetTodo(ctx context.Context, arg GetTodoParams) (Todo, error) {
	row := q.db.QueryRowContext(ctx, getTodo, arg.ID, arg.UserID)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.Title,
		&i.Notes,
		&i.Priority,
		&i.Status,
		&i.DueAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EstimateMinutes,
		&i.Position,
		&i.RecurrenceFreq,
		&i.RecurrenceInterval,
		&i.SpawnedFromID,
		&i.RecurrenceUntil,
		&i.RecurrenceRemaining,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT id, user_id, name, color, created_at, updated_at FROM todo_projects
WHERE user_id = $1
ORDER BY name
`

func (q *Queries) ListProjects(ctx context.Context, userID int64) ([]TodoProject, error) {
	rows, err := q.db.QueryContext(ctx, listProjects, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TodoProject{}
	for rows.Next() {
		var i TodoProject
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Color,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecurrenceDaysForTodo = `-- name: ListRecurrenceDaysForTodo :many
SELECT weekday FROM todo_recurrence_days
WHERE todo_id = $1
ORDER BY weekday
`

func (q *Queries) ListRecurrenceDaysForTodo(ctx context.Context, todoID int64) ([]int16, error) {
	rows, err := q.db.QueryContext(ctx, listRecurrenceDaysForTodo, todoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int16{}
	for rows.Next() {
		var weekday int16
		if err := rows.Scan(&weekday); err != nil {
			return nil, err
		}
		items = append(items, weekday)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecurrenceDaysForUserTodos = `-- name: ListRecurrenceDaysForUserTodos :many
SELECT d.todo_id, d.weekday FROM todo_recurrence_days d
JOIN todos t ON t.id = d.todo_id
WHERE t.user_id = $1
ORDER BY d.todo_id, d.weekday
`

// Every (todo, weekday) pair for the user, so the list endpoint can embed the
// weekday rules in one round-trip instead of a query per row — the same shape
// ListTagsForUserTodos uses.
func (q *Queries) ListRecurrenceDaysForUserTodos(ctx context.Context, userID int64) ([]TodoRecurrenceDay, error) {
	rows, err := q.db.QueryContext(ctx, listRecurrenceDaysForUserTodos, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TodoRecurrenceDay{}
	for rows.Next() {
		var i TodoRecurrenceDay
		if err := rows.Scan(&i.TodoID, &i.Weekday); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTags = `-- name: ListTags :many
SELECT id, user_id, name FROM todo_tags
WHERE user_id = $1
ORDER BY name
`

func (q *Queries) ListTags(ctx context.Context, userID int64) ([]TodoTag, error) {
	rows, err := q.db.QueryContext(ctx, listTags, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TodoTag{}
	for rows.Next() {
		var i TodoTag
		if err := rows.Scan(&i.ID, &i.UserID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsForTodo = `-- name: ListTagsForTodo :many
SELECT t.id, t.user_id, t.name FROM todo_tags t
JOIN todo_tag_map m ON m.tag_id = t.id
WHERE m.todo_id = $1
ORDER BY t.name
`

func (q *Queries) ListTagsForTodo(ctx context.Context, todoID int64) ([]TodoTag, error) {
	rows, err := q.db.QueryContext(ctx, listTagsForTodo, todoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TodoTag{}
	for rows.Next() {
		var i TodoTag
		if err := rows.Scan(&i.ID, &i.UserID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsForUserTodos = `-- name: ListTagsForUserTodos :many
SELECT m.todo_id, t.id, t.name FROM todo_tags t
JOIN todo_tag_map m ON m.tag_id = t.id
WHERE t.user_id = $1
ORDER BY m.todo_id, t.name
`

type ListTagsForUserTodosRow struct {
	TodoID int64  `json:"todo_id"`
	ID     int64  `json:"id"`
	Name   string `json:"name"`
}

// Every (todo, tag) link for the user, so the todo list can embed tags in one round-trip.
func (q *Queries) ListTagsForUserTodos(ctx context.Context, userID int64) ([]ListTagsForUserTodosRow, error) {
	rows, err := q.db.QueryContext(ctx, listTagsForUserTodos, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTagsForUserTodosRow{}
	for rows.Next() {
		var i ListTagsForUserTodosRow
		if err := rows.Scan(&i.TodoID, &i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTagFromTodo = `-- name: RemoveTagFromTodo :exec
DELETE FROM todo_tag_map
WHERE todo_id = $1 AND tag_id = $2
`

type RemoveTagFromTodoParams struct {
	TodoID int64 `json:"todo_id"`
	TagID  int64 `json:"tag_id"`
}

func (q *Queries) RemoveTagFromTodo(ctx context.Context, arg RemoveTagFromTodoParams) error {
	_, err := q.db.ExecContext(ctx, removeTagFromTodo, arg.TodoID, arg.TagID)
	return err
}

const setTodoPosition = `-- name: SetTodoPosition :execrows
UPDATE todos
SET position = $1, updated_at = now()
WHERE id = $2 AND user_id = $3
`

type SetTodoPositionParams struct {
	Position int64 `json:"position"`
	ID       int64 `json:"id"`
	UserID   int64 `json:"user_id"`
}

// Used by the reorder endpoint inside a transaction. Scoped by user_id, so a
// foreign id touches no rows (the handler treats 0 affected rows as not-owned).
func (q *Queries) SetTodoPosition(ctx context.Context, arg SetTodoPositionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setTodoPosition, arg.Position, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setTodoRecurrenceEnd = `-- name: SetTodoRecurrenceEnd :exec
UPDATE todos
SET recurrence_until = $1, recurrence_remaining = $2, updated_at = now()
WHERE id = $3 AND user_id = $4
`

type SetTodoRecurrenceEndParams struct {
	RecurrenceUntil     sql.NullTime  `json:"recurrence_until"`
	RecurrenceRemaining sql.NullInt32 `json:"recurrence_remaining"`
	ID                  int64         `json:"id"`
	UserID              int64         `json:"user_id"`
}

// The two end-of-series columns move separately from the rest of the update, so
// the handler can leave them alone when a request doesn't carry a rule at all.
func (q *Queries) SetTodoRecurrenceEnd(ctx context.Context, arg SetTodoRecurrenceEndParams) error {
	_, err := q.db.ExecContext(ctx, setTodoRecurrenceEnd,
		arg.RecurrenceUntil,
		arg.RecurrenceRemaining,
		arg.ID,
		arg.UserID,
	)
	return err
}

const updateProject = `-- name: UpdateProject :one
UPDATE todo_projects
SET name = $1, color = $2, updated_at = now()
WHERE id = $3 AND user_id = $4
RETURNING id, user_id, name, color, created_at, updated_at
`

type UpdateProjectParams struct {
	Name   string `json:"name"`
	Color  string `json:"color"`
	ID     int64  `json:"id"`
	UserID int64  `json:"user_id"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (TodoProject, error) {
	row := q.db.QueryRowContext(ctx, updateProject,
		arg.Name,
		arg.Color,
		arg.ID,
		arg.UserID,
	)
	var i TodoProject
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTodo = `-- name: UpdateTodo :one

UPDATE todos
SET project_id = $1, title = $2, notes = $3, priority = $4, status = $5, due_at = $6, estimate_minutes = $7,
    recurrence_freq = $8, recurrence_interval = $9, updated_at = now()
WHERE id = $10 AND user_id = $11
RETURNING id, user_id, project_id, title, notes, priority, status, due_at, created_at, updated_at, estimate_minutes, position, recurrence_freq, recurrence_interval, spawned_from_id, recurrence_until, recurrence_remaining
`

type UpdateTodoParams struct {
	ProjectID          sql.NullInt64  `json:"project_id"`
	Title              string         `json:"title"`
	Notes              string         `json:"notes"`
	Priority           int32          `json:"priority"`
	Status             string         `json:"status"`
	DueAt              sql.NullTime   `json:"due_at"`
	EstimateMinutes    sql.NullInt32  `json:"estimate_minutes"`
	RecurrenceFreq     sql.NullString `json:"recurrence_freq"`
	RecurrenceInterval int32          `json:"recurrence_interval"`
	ID                 int64          `json:"id"`
	UserID             int64          `json:"user_id"`
}

// The todo list is sorted dynamically in Go (a whitelisted ORDER BY), so there
// is no fixed ListTodos query here.
func (q *Queries) UpdateTodo(ctx context.Context, arg UpdateTodoParams) (Todo, error) {
	row := q.db.QueryRowContext(ctx, updateTodo,
		arg.ProjectID,
		arg.Title,
		arg.Notes,
		arg.Priority,
		arg.Status,
		arg.DueAt,
		arg.EstimateMinutes,
		arg.RecurrenceFreq,
		arg.RecurrenceInterval,
		arg.ID,
		arg.UserID,
	)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.Title,
		&i.Notes,
		&i.Priority,
		&i.Status,
		&i.DueAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EstimateMinutes,
		&i.Position,
		&i.RecurrenceFreq,
		&i.RecurrenceInterval,
		&i.SpawnedFromID,
		&i.RecurrenceUntil,
		&i.RecurrenceRemaining,
	)
	return i, err
}
